# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Delete_Duplicate
                                 A QGIS plugin
 Delete duplicate or redundant fields from a vector file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-04
        copyright            : (C) 2023 by Blair William Gerald Scriven
        email                : scrivenblair@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Delete_Duplicate class from file Delete_Duplicate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Delete_Duplicates import Delete_Duplicate
    return Delete_Duplicate(iface)
